#include<iostream.h>

main()
{
 int i;
 float a;
 char c;

 cout << "Enter a number between 1 and 100: ";
 cin >> i;
 cout << "You entered " << i << '\n';

 cout << "Enter the most recent unleaded gas price you have seen: $";
 cin >> a;
 cout << "You entered " << a << '\n';

 cout << "Enter the first letter of your last name: ";
 cin >> c;
 cout << "You entered " << c << '\n';

 return 0;
}
